import { Routes } from '@angular/router';
import { adminGuard, doctorGuard, homeGuard, patientGuard, queueBoardGuard, receptionGuard, roomManagerGuard, staffLandingRedirect } from './core/auth/auth.guard';

export const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'home' },
  { path: 'home', loadComponent: () => import('./features/home/home').then((m) => m.Home), canActivate: [homeGuard] },
  { path: 'login', loadComponent: () => import('./features/auth/login/login').then((m) => m.Login) },
  { path: 'recover-password', loadComponent: () => import('./features/auth/recover-password/recover-password').then((m) => m.RecoverPassword) },
  { path: 'staff/login', loadComponent: () => import('./features/staff-auth/staff-login').then((m) => m.StaffLogin) },
  { path: 'doctor', loadComponent: () => import('./features/staff-dashboard/staff-dashboard').then((m) => m.StaffDashboard), canActivate: [doctorGuard] },
  { path: 'staff', pathMatch: 'full', redirectTo: staffLandingRedirect },
  { path: 'doctor/examinations/:ticketId', loadComponent: () => import('./features/doctor-examination/doctor-examination').then((m) => m.DoctorExamination), canActivate: [doctorGuard] },
  { path: 'register', loadComponent: () => import('./features/auth/register/register').then((m) => m.Register) },
  { path: 'account', loadComponent: () => import('./features/account/account').then((m) => m.Account), canActivate: [patientGuard] },
  { path: 'change-password', loadComponent: () => import('./features/auth/change-password/change-password').then((m) => m.ChangePassword), canActivate: [patientGuard] },
  { path: 'appointments/new', loadComponent: () => import('./features/appointments/booking/booking').then((m) => m.Booking), canActivate: [patientGuard] },
  { path: 'appointments', loadComponent: () => import('./features/appointments/list/appointments-list').then((m) => m.AppointmentsList), canActivate: [patientGuard] },
  { path: 'appointments/:id', loadComponent: () => import('./features/appointments/detail/appointment-detail').then((m) => m.AppointmentDetail), canActivate: [patientGuard] },
  { path: 'queue/check-in/:roomCode', loadComponent: () => import('./features/queue/check-in/queue-check-in').then((m) => m.QueueCheckIn), canActivate: [patientGuard] },
  { path: 'queue/rooms/:roomCode', loadComponent: () => import('./features/queue/board/queue-board').then((m) => m.QueueBoard), canActivate: [queueBoardGuard] },
  { path: 'reception', loadComponent: () => import('./features/reception/check-in/reception-check-in').then((m) => m.ReceptionCheckIn), canActivate: [receptionGuard], data: { receptionView: 'overview' } },
  { path: 'reception/appointments', loadComponent: () => import('./features/reception/check-in/reception-check-in').then((m) => m.ReceptionCheckIn), canActivate: [receptionGuard], data: { receptionView: 'search' } },
  { path: 'reception/walk-in', loadComponent: () => import('./features/reception/check-in/reception-check-in').then((m) => m.ReceptionCheckIn), canActivate: [receptionGuard], data: { receptionView: 'intake' } },
  { path: 'reception/queue', loadComponent: () => import('./features/reception/check-in/reception-check-in').then((m) => m.ReceptionCheckIn), canActivate: [receptionGuard], data: { receptionView: 'queue' } },
  { path: 'reception/exceptions', loadComponent: () => import('./features/reception/check-in/reception-check-in').then((m) => m.ReceptionCheckIn), canActivate: [receptionGuard], data: { receptionView: 'exceptions' } },
  { path: 'reception/profiles', loadComponent: () => import('./features/reception/check-in/reception-check-in').then((m) => m.ReceptionCheckIn), canActivate: [receptionGuard], data: { receptionView: 'profiles' } },
  { path: 'reception/check-in', pathMatch: 'full', redirectTo: 'reception/appointments' },
  { path: 'medical-records', loadComponent: () => import('./features/medical-records/medical-records').then((m) => m.MedicalRecords), canActivate: [patientGuard] },
  { path: 'medical-records/:id', loadComponent: () => import('./features/medical-records/medical-record-detail').then((m) => m.MedicalRecordDetail), canActivate: [patientGuard] },
  { path: 'patient-profiles', loadComponent: () => import('./features/patient-profiles/patient-profiles').then((m) => m.PatientProfiles), canActivate: [patientGuard] },
  { path: 'notifications', loadComponent: () => import('./features/notifications/notifications').then((m) => m.Notifications), canActivate: [patientGuard] },
  { path: 'admin/rooms', loadComponent: () => import('./features/room-management/room-management').then((m) => m.RoomManagement), canActivate: [roomManagerGuard] },
  { path: 'admin/doctors', loadComponent: () => import('./features/doctor-management/doctor-management').then((m) => m.DoctorManagement), canActivate: [roomManagerGuard] },
  { path: 'admin/services', loadComponent: () => import('./features/service-management/service-management').then((m) => m.ServiceManagement), canActivate: [roomManagerGuard] },
  { path: 'admin/specialties', loadComponent: () => import('./features/specialty-catalog-management/specialty-catalog-management').then((m) => m.SpecialtyCatalogManagement), canActivate: [roomManagerGuard] },
  { path: 'admin/medical-record-templates', loadComponent: () => import('./features/medical-record-template-management/medical-record-template-management').then((m) => m.MedicalRecordTemplateManagement), canActivate: [roomManagerGuard] },
  { path: 'admin/sms-deliveries', loadComponent: () => import('./features/sms-delivery-management/sms-delivery-management').then((m) => m.SmsDeliveryManagement), canActivate: [adminGuard] },
  { path: 'admin/schedule-templates', loadComponent: () => import('./features/schedule-template-management/schedule-template-management').then((m) => m.ScheduleTemplateManagement), canActivate: [roomManagerGuard] },
  { path: 'admin/staff', loadComponent: () => import('./features/staff-management/staff-management').then((m) => m.StaffManagement), canActivate: [adminGuard] },
  { path: 'admin/statistics', loadComponent: () => import('./features/admin-statistics/admin-statistics').then((m) => m.AdminStatistics), canActivate: [roomManagerGuard] },
  { path: 'admin/rescheduling', loadComponent: () => import('./features/rescheduling/rescheduling').then((m) => m.Rescheduling), canActivate: [roomManagerGuard] },
  { path: 'admin/doctor-time-off', loadComponent: () => import('./features/doctor-time-off/doctor-time-off').then((m) => m.DoctorTimeOffManagement), canActivate: [roomManagerGuard] },
  { path: 'admin/reconciliations', loadComponent: () => import('./features/reconciliation/reconciliation').then((m) => m.ReconciliationManagement), canActivate: [roomManagerGuard] },
  { path: 'admin/access-audit', loadComponent: () => import('./features/access-audit/access-audit').then((m) => m.AccessAuditManagement), canActivate: [adminGuard] },
  { path: 'admin/configuration', loadComponent: () => import('./features/clinic-configuration/clinic-configuration').then((m) => m.ClinicConfiguration), canActivate: [adminGuard] },
  { path: 'admin/reason-catalog', loadComponent: () => import('./features/reason-catalog-management/reason-catalog-management').then((m) => m.ReasonCatalogManagement), canActivate: [adminGuard] },
  { path: 'admin/medications', loadComponent: () => import('./features/medication-catalog-management/medication-catalog-management').then((m) => m.MedicationCatalogManagement), canActivate: [adminGuard] },
  { path: 'admin/diagnoses', loadComponent: () => import('./features/diagnosis-catalog-management/diagnosis-catalog-management').then((m) => m.DiagnosisCatalogManagement), canActivate: [adminGuard] },
  { path: 'admin/business-audit', loadComponent: () => import('./features/business-audit/business-audit').then((m) => m.BusinessAudit), canActivate: [roomManagerGuard] },
  { path: 'about', loadComponent: () => import('./features/public/public-page').then((m) => m.PublicPage), data: { page: 'about' } },
  { path: 'process', loadComponent: () => import('./features/public/public-page').then((m) => m.PublicPage), data: { page: 'process' } },
  { path: 'common-issues', loadComponent: () => import('./features/public/public-page').then((m) => m.PublicPage), data: { page: 'common-issues' } },
  { path: 'support', loadComponent: () => import('./features/public/public-page').then((m) => m.PublicPage), data: { page: 'support' } },
  { path: 'contact', loadComponent: () => import('./features/public/public-page').then((m) => m.PublicPage), data: { page: 'contact' } },
  { path: 'dashboard', loadComponent: () => import('./features/dashboard/dashboard').then((m) => m.Dashboard), canActivate: [patientGuard] },
  { path: '**', redirectTo: 'home' },
];
