package com.clinicone.notification;

public enum PatientNotificationType {
    MEDICAL_RECORD_SIGNED,
    APPOINTMENT_CREATED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_REMINDER_24H,
    APPOINTMENT_REMINDER_2H,
    APPOINTMENT_LATE_WARNING,
    APPOINTMENT_ABSENT
}
